version: "3.9"

volumes:
  db-data: {}

services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=log-analytics-user
      - MYSQL_PASSWORD=log-analytics-password
      - MYSQL_DATABASE=log-analytics-api
    volumes:
      - db-data:/var/lib/mysql

  app:
    image: ghcr.io/fpetrovic/log-analytics-api/app:latest
    tty: true
    environment:
      APP_ENV: dev
    depends_on:
      - db
    volumes:
      - ./:/app:rw
      - ./docker/php/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint:ro

  proxy:
    image: ghcr.io/fpetrovic/log-analytics-api/proxy:latest
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - app
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/local_certs:/etc/letsencrypt:ro
      - ./log:/var/log/nginx
